### ISSUE TITLE
FRC 42 hash function

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/go-state-types#128]
implement the FRC-0042 hashing functionality in this repo.

**Comment by arajasek** [comment]
[FRC-0042](https://github.com/filecoin-project/FIPs/blob/master/FRCs/frc-0042.md) introduced a convention to convert Method Names to Method Numbers. The algorithm is outlined [here](https://github.com/filecoin-project/FIPs/blob/master/FRCs/frc-0042.md#method-number-computation), and its Rust implementation can be found [here](https://github.com/helix-onchain/filecoin/blob/9c7aa8b20a38d260eb94fda8b85a2a0aefef609f/frc42_dispatch/hasher/src/hash.rs#L70-L99).

This standard became adopted by built-in actors in nv17 (v9 actors) for a single method, the UniversalReceiverHook. In order to move quickly, we simply special-cased this as [a magic number in this repo](https://github.com/filecoin-project/go-state-types/blob/3ee9fb7d0a8254ad98bbdebca7b005f077701dbe/builtin/methods.go#L10). 

nv18 (v10 actors) will add many more such methods, so we need to actually implement this algorithm in Go (lest we have literally dozens of such magic numbers).

**Comment by shrenujbansal** [comment]
@arajasek Do you just need the this hash function implemented or does it also need to be integrated somewhere?

**Comment by jennijuju** [comment]
@shrenujbansal yes in a lotus cli please

**Comment by jennijuju** [comment]
(I wont mind an API tbh but I think @arajasek may hate that idea
